name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fattfatt/nimfinder:latest

  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Pull image and run docker via ssh
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/nimfinder
          git pull origin master
          cat << EOF > .env 
          SERVICE_NAME=${{ secrets.SERVICE_NAME }}
          PORT=${{ secrets.PORT }}
          MONGO_HOST=${{ secrets.MONGO_HOST }}
          MONGO_DB=${{ secrets.MONGO_DB }}
          EOF
          docker-compose pull
          docker-compose down
          docker-compose up -d

